/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings worker-bindings.d.ts` (hash: 75a3e49e3aa59277c040db4fef91819e)
interface __BaseEnv_CloudflareBindings {
	JOURNAL_ARCHIVE_BUCKET: R2Bucket;
	CONTENT_BUCKET: R2Bucket;
	PROJECTION_QUEUE: Queue;
	BOT_WAKE_QUEUE: Queue;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	DESKTOP_SOCIAL_LOOP_ENABLED: "true" | "false";
	ENVIRONMENT: "staging" | "local";
	JOURNAL_HOT_EVENTS: "1000";
	JOURNAL_SEGMENT_EVENTS: "250";
	OPERATOR_PROVISIONING_TOKEN: string;
	ATTESTATION_PUBLIC_KEYS_JSON: string;
	MESSAGE_SEARCH_MASTER_KEY: string;
	MESSAGE_SEARCH_CURSOR_KEY: string;
	MESSAGE_HISTORY_CURSOR_KEY: string;
	DIRECTORY_CURSOR_KEY: string;
	MEDIA_UPLOAD_GRANT_KEY: string;
	WORKSPACES: DurableObjectNamespace<import("./src/index").WorkspaceDO>;
	WORKSPACE_SLUGS: DurableObjectNamespace<import("./src/index").WorkspaceSlugDO>;
	BOTS: DurableObjectNamespace<import("./src/index").BotDO>;
	BOT_SLUGS: DurableObjectNamespace<import("./src/index").BotSlugDO>;
	BOT_INSTALLATIONS: DurableObjectNamespace<import("./src/index").BotInstallationDO>;
	CONVERSATIONS: DurableObjectNamespace<import("./src/index").ConversationDO>;
	CONVERSATION_IDENTITIES: DurableObjectNamespace<import("./src/index").ConversationIdentityDO>;
	MESSAGE_CONTENT: DurableObjectNamespace<import("./src/index").MessageContentDO>;
	MEDIA_UPLOADS: DurableObjectNamespace<import("./src/index").MediaUploadDO>;
	PRESENCE: DurableObjectNamespace<import("./src/index").PresenceDO>;
	AUTH_RUNTIME_IDENTITY: Service /* entrypoint RuntimeIdentityService from punks-auth-staging */ | Service /* entrypoint RuntimeIdentityService from punks-auth */;
	ATTESTATION_RUNTIME_IDENTITY: Service /* entrypoint RuntimeIdentityService from punks-attestation-staging */ | Service /* entrypoint RuntimeIdentityService from punks-attestation */;
	ERASURE_RUNTIME_IDENTITY: Service /* entrypoint RuntimeIdentityService from punks-erasure-staging */ | Service /* entrypoint RuntimeIdentityService from punks-erasure */;
	PROJECTOR_RUNTIME_IDENTITY: Service /* entrypoint RuntimeIdentityService from punks-projector-staging */ | Service /* entrypoint RuntimeIdentityService from punks-projector */;
	SEARCH_RUNTIME_IDENTITY: Service /* entrypoint RuntimeIdentityService from punks-search-staging */ | Service /* entrypoint RuntimeIdentityService from punks-search */;
	BOT_RUNTIME_IDENTITY: Service /* entrypoint RuntimeIdentityService from punks-bot-runtime-staging */ | Service /* entrypoint RuntimeIdentityService from punks-bot-runtime */;
	ATTESTATION: Fetcher /* punks-attestation-staging */ | Fetcher /* punks-attestation */;
	AUTH_SERVICE: Service /* entrypoint PunkSessionService from punks-auth-staging */ | Service /* entrypoint PunkSessionService from punks-auth */;
	WORKSPACE_OWNERSHIP_AUTHORITY: Service /* entrypoint WorkspaceOwnershipAuthorizationService from punks-auth-staging */ | Service /* entrypoint WorkspaceOwnershipAuthorizationService from punks-auth */;
	ACCOUNT_MERGE_AUTHORITY: Service /* entrypoint AccountMergePlanningService from punks-auth-staging */ | Service /* entrypoint AccountMergePlanningService from punks-auth */;
	ACCOUNT_MERGE_RIGHTS_INDEX: Service /* entrypoint AccountMergeRightsIndexService from punks-auth-staging */ | Service /* entrypoint AccountMergeRightsIndexService from punks-auth */;
	BOT_INVOCATION_VERIFIER: Service /* entrypoint BotInvocationVerifier from punks-auth-staging */ | Service /* entrypoint BotInvocationVerifier from punks-auth */;
	ERASURE_REGISTRY: Fetcher /* punks-erasure-staging */ | Fetcher /* punks-erasure */;
	MESSAGE_SEARCH: Fetcher /* punks-search-staging */ | Fetcher /* punks-search */;
	PROJECTION_DIRECTORY: Service /* entrypoint ProjectionDirectoryService from punks-projector-staging */ | Service /* entrypoint ProjectionDirectoryService from punks-projector */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "WorkspaceDO" | "WorkspaceSlugDO" | "ConversationDO" | "ConversationIdentityDO" | "MessageContentDO" | "BotDO" | "BotSlugDO" | "BotInstallationDO" | "MediaUploadDO" | "PresenceDO";
	}
	interface StagingEnv {
		JOURNAL_ARCHIVE_BUCKET: R2Bucket;
		CONTENT_BUCKET: R2Bucket;
		PROJECTION_QUEUE: Queue;
		BOT_WAKE_QUEUE: Queue;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		DESKTOP_SOCIAL_LOOP_ENABLED: "true";
		ENVIRONMENT: "staging";
		JOURNAL_HOT_EVENTS: "1000";
		JOURNAL_SEGMENT_EVENTS: "250";
		OPERATOR_PROVISIONING_TOKEN: string;
		ATTESTATION_PUBLIC_KEYS_JSON: string;
		MESSAGE_SEARCH_MASTER_KEY: string;
		MESSAGE_SEARCH_CURSOR_KEY: string;
		MESSAGE_HISTORY_CURSOR_KEY: string;
		DIRECTORY_CURSOR_KEY: string;
		MEDIA_UPLOAD_GRANT_KEY: string;
		WORKSPACES: DurableObjectNamespace<import("./src/index").WorkspaceDO>;
		WORKSPACE_SLUGS: DurableObjectNamespace<import("./src/index").WorkspaceSlugDO>;
		BOTS: DurableObjectNamespace<import("./src/index").BotDO>;
		BOT_SLUGS: DurableObjectNamespace<import("./src/index").BotSlugDO>;
		BOT_INSTALLATIONS: DurableObjectNamespace<import("./src/index").BotInstallationDO>;
		CONVERSATIONS: DurableObjectNamespace<import("./src/index").ConversationDO>;
		CONVERSATION_IDENTITIES: DurableObjectNamespace<import("./src/index").ConversationIdentityDO>;
		MESSAGE_CONTENT: DurableObjectNamespace<import("./src/index").MessageContentDO>;
		MEDIA_UPLOADS: DurableObjectNamespace<import("./src/index").MediaUploadDO>;
		PRESENCE: DurableObjectNamespace<import("./src/index").PresenceDO>;
		AUTH_RUNTIME_IDENTITY: Service /* entrypoint RuntimeIdentityService from punks-auth-staging */;
		ATTESTATION_RUNTIME_IDENTITY: Service /* entrypoint RuntimeIdentityService from punks-attestation-staging */;
		ERASURE_RUNTIME_IDENTITY: Service /* entrypoint RuntimeIdentityService from punks-erasure-staging */;
		PROJECTOR_RUNTIME_IDENTITY: Service /* entrypoint RuntimeIdentityService from punks-projector-staging */;
		SEARCH_RUNTIME_IDENTITY: Service /* entrypoint RuntimeIdentityService from punks-search-staging */;
		BOT_RUNTIME_IDENTITY: Service /* entrypoint RuntimeIdentityService from punks-bot-runtime-staging */;
		ATTESTATION: Fetcher /* punks-attestation-staging */;
		AUTH_SERVICE: Service /* entrypoint PunkSessionService from punks-auth-staging */;
		WORKSPACE_OWNERSHIP_AUTHORITY: Service /* entrypoint WorkspaceOwnershipAuthorizationService from punks-auth-staging */;
		ACCOUNT_MERGE_AUTHORITY: Service /* entrypoint AccountMergePlanningService from punks-auth-staging */;
		ACCOUNT_MERGE_RIGHTS_INDEX: Service /* entrypoint AccountMergeRightsIndexService from punks-auth-staging */;
		BOT_INVOCATION_VERIFIER: Service /* entrypoint BotInvocationVerifier from punks-auth-staging */;
		ERASURE_REGISTRY: Fetcher /* punks-erasure-staging */;
		MESSAGE_SEARCH: Fetcher /* punks-search-staging */;
		PROJECTION_DIRECTORY: Service /* entrypoint ProjectionDirectoryService from punks-projector-staging */;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DESKTOP_SOCIAL_LOOP_ENABLED" | "ENVIRONMENT" | "JOURNAL_HOT_EVENTS" | "JOURNAL_SEGMENT_EVENTS" | "OPERATOR_PROVISIONING_TOKEN" | "ATTESTATION_PUBLIC_KEYS_JSON" | "MESSAGE_SEARCH_MASTER_KEY" | "MESSAGE_SEARCH_CURSOR_KEY" | "MESSAGE_HISTORY_CURSOR_KEY" | "DIRECTORY_CURSOR_KEY" | "MEDIA_UPLOAD_GRANT_KEY">> {}
}
