/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings worker-bindings.d.ts` (hash: b8b050827a9ee4ee905ba859f8ba4380)
interface __BaseEnv_CloudflareBindings {
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "staging" | "local";
	PROMOTION_SESSION_ISSUANCE_ENABLED: "true" | "false";
	BOT_INVOCATION_CURRENT_KID: "staging-v1" | "local-v1";
	AUTH_BASE_URL: "https://staging.punks.bot" | "http://localhost:1420";
	SESSION_TTL_SECONDS: "2592000";
	GOOGLE_AUTHORIZATION_ENDPOINT: "https://accounts.google.com/o/oauth2/v2/auth";
	GOOGLE_TOKEN_ENDPOINT: "https://oauth2.googleapis.com/token";
	GOOGLE_USERINFO_ENDPOINT: "https://openidconnect.googleapis.com/v1/userinfo";
	GITHUB_AUTHORIZATION_ENDPOINT: "https://github.com/login/oauth/authorize";
	GITHUB_TOKEN_ENDPOINT: "https://github.com/login/oauth/access_token";
	GITHUB_API_BASE_URL: "https://api.github.com";
	GOOGLE_OAUTH_CLIENT_ID: string;
	GOOGLE_OAUTH_CLIENT_SECRET: string;
	GITHUB_OAUTH_CLIENT_ID: string;
	GITHUB_OAUTH_CLIENT_SECRET: string;
	BOT_INVOCATION_CURRENT_SECRET: string;
	PUNKS: DurableObjectNamespace<import("./src/index").PunkDO>;
	ACCOUNT_MERGE_INTENTS: DurableObjectNamespace<import("./src/index").AccountMergeIntentDO>;
	IDENTITY_CLAIMS: DurableObjectNamespace<import("./src/index").IdentityClaimDO>;
	EMAIL_CLAIMS: DurableObjectNamespace<import("./src/index").EmailClaimDO>;
	AUTH_TRANSACTIONS: DurableObjectNamespace<import("./src/index").AuthTransactionDO>;
	DESKTOP_AUTH_FLOWS: DurableObjectNamespace<import("./src/index").DesktopAuthFlowDO>;
	DESKTOP_REAUTH_GRANTS: DurableObjectNamespace<import("./src/index").DesktopReauthGrantDO>;
	SESSION_REVOCATIONS: DurableObjectNamespace<import("./src/index").SessionRevocationDO>;
	SESSION_ROTATIONS: DurableObjectNamespace<import("./src/index").SessionRotationDO>;
	SESSIONS: DurableObjectNamespace<import("./src/index").SessionDO>;
	ACCOUNT_MERGE_RECEIPTS: Service /* entrypoint AccountMergeReceiptRegistryService from punks-erasure-staging */ | Service /* entrypoint AccountMergeReceiptRegistryService from punks-erasure */;
	ACCOUNT_MERGE_WORKSPACES: Service /* entrypoint AccountMergeWorkspaceService from punks-api-staging */ | Service /* entrypoint AccountMergeWorkspaceService from punks-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "PunkDO" | "IdentityClaimDO" | "EmailClaimDO" | "AuthTransactionDO" | "SessionDO" | "AccountMergeIntentDO" | "DesktopAuthFlowDO" | "DesktopReauthGrantDO" | "SessionRevocationDO" | "SessionRotationDO";
	}
	interface StagingEnv {
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "staging";
		PROMOTION_SESSION_ISSUANCE_ENABLED: "true";
		BOT_INVOCATION_CURRENT_KID: "staging-v1";
		AUTH_BASE_URL: "https://staging.punks.bot";
		SESSION_TTL_SECONDS: "2592000";
		GOOGLE_AUTHORIZATION_ENDPOINT: "https://accounts.google.com/o/oauth2/v2/auth";
		GOOGLE_TOKEN_ENDPOINT: "https://oauth2.googleapis.com/token";
		GOOGLE_USERINFO_ENDPOINT: "https://openidconnect.googleapis.com/v1/userinfo";
		GITHUB_AUTHORIZATION_ENDPOINT: "https://github.com/login/oauth/authorize";
		GITHUB_TOKEN_ENDPOINT: "https://github.com/login/oauth/access_token";
		GITHUB_API_BASE_URL: "https://api.github.com";
		GOOGLE_OAUTH_CLIENT_ID: string;
		GOOGLE_OAUTH_CLIENT_SECRET: string;
		GITHUB_OAUTH_CLIENT_ID: string;
		GITHUB_OAUTH_CLIENT_SECRET: string;
		BOT_INVOCATION_CURRENT_SECRET: string;
		PUNKS: DurableObjectNamespace<import("./src/index").PunkDO>;
		ACCOUNT_MERGE_INTENTS: DurableObjectNamespace<import("./src/index").AccountMergeIntentDO>;
		IDENTITY_CLAIMS: DurableObjectNamespace<import("./src/index").IdentityClaimDO>;
		EMAIL_CLAIMS: DurableObjectNamespace<import("./src/index").EmailClaimDO>;
		AUTH_TRANSACTIONS: DurableObjectNamespace<import("./src/index").AuthTransactionDO>;
		DESKTOP_AUTH_FLOWS: DurableObjectNamespace<import("./src/index").DesktopAuthFlowDO>;
		DESKTOP_REAUTH_GRANTS: DurableObjectNamespace<import("./src/index").DesktopReauthGrantDO>;
		SESSION_REVOCATIONS: DurableObjectNamespace<import("./src/index").SessionRevocationDO>;
		SESSION_ROTATIONS: DurableObjectNamespace<import("./src/index").SessionRotationDO>;
		SESSIONS: DurableObjectNamespace<import("./src/index").SessionDO>;
		ACCOUNT_MERGE_RECEIPTS: Service /* entrypoint AccountMergeReceiptRegistryService from punks-erasure-staging */;
		ACCOUNT_MERGE_WORKSPACES: Service /* entrypoint AccountMergeWorkspaceService from punks-api-staging */;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "PROMOTION_SESSION_ISSUANCE_ENABLED" | "BOT_INVOCATION_CURRENT_KID" | "AUTH_BASE_URL" | "SESSION_TTL_SECONDS" | "GOOGLE_AUTHORIZATION_ENDPOINT" | "GOOGLE_TOKEN_ENDPOINT" | "GOOGLE_USERINFO_ENDPOINT" | "GITHUB_AUTHORIZATION_ENDPOINT" | "GITHUB_TOKEN_ENDPOINT" | "GITHUB_API_BASE_URL" | "GOOGLE_OAUTH_CLIENT_ID" | "GOOGLE_OAUTH_CLIENT_SECRET" | "GITHUB_OAUTH_CLIENT_ID" | "GITHUB_OAUTH_CLIENT_SECRET" | "BOT_INVOCATION_CURRENT_SECRET">> {}
}
