/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings worker-bindings.d.ts` (hash: fc906a28217f442fb5c8ce75fe31e209)
interface __BaseEnv_CloudflareBindings {
	PROJECTION_DB_0: D1Database;
	PROJECTION_DB_1: D1Database;
	PROJECTION_DB_2: D1Database;
	PROJECTION_DB_3: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "local" | "staging";
	D1_SHARD_COUNT: "4";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface LocalEnv {
		PROJECTION_DB_0: D1Database;
		PROJECTION_DB_1: D1Database;
		PROJECTION_DB_2: D1Database;
		PROJECTION_DB_3: D1Database;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "local";
		D1_SHARD_COUNT: "4";
	}
	interface StagingEnv {
		PROJECTION_DB_0: D1Database;
		PROJECTION_DB_1: D1Database;
		PROJECTION_DB_2: D1Database;
		PROJECTION_DB_3: D1Database;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "staging";
		D1_SHARD_COUNT: "4";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "D1_SHARD_COUNT">> {}
}
