/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings worker-bindings.d.ts` (hash: 888ab0066a047367c18e128d6454c99d)
interface __BaseEnv_CloudflareBindings {
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "staging" | "local";
	ATTESTATION_KEY_VERSION: "staging-v1" | "local-v1";
	ATTESTATION_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "staging";
		ATTESTATION_KEY_VERSION: "staging-v1";
		ATTESTATION_PRIVATE_KEY: string;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "ATTESTATION_KEY_VERSION" | "ATTESTATION_PRIVATE_KEY">> {}
}
