/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings worker-bindings.d.ts` (hash: acf1cdda5994e2f9fb7ca29895300f1c)
interface __BaseEnv_CloudflareBindings {
	AI?: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "staging" | "local";
	BOT_INVOCATION_ISSUER: Service /* entrypoint BotInvocationIssuer from punks-auth-staging */ | Service /* entrypoint BotInvocationIssuer from punks-auth */;
	BOT_ACTION_SERVICE: Service /* entrypoint BotActionService from punks-api-staging */ | Service /* entrypoint BotActionService from punks-api */;
	BOT_HARNESS_SERVICE: Service /* entrypoint BotHarnessService from punks-api-staging */ | Service /* entrypoint BotHarnessService from punks-api */;
	BOT_WAKE_WORKFLOW: Workflow<Parameters<import("./src/index").BotWakeWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		AI: Ai;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "staging";
		BOT_INVOCATION_ISSUER: Service /* entrypoint BotInvocationIssuer from punks-auth-staging */;
		BOT_ACTION_SERVICE: Service /* entrypoint BotActionService from punks-api-staging */;
		BOT_HARNESS_SERVICE: Service /* entrypoint BotHarnessService from punks-api-staging */;
		BOT_WAKE_WORKFLOW: Workflow<Parameters<import("./src/index").BotWakeWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
