/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings worker-bindings.d.ts` (hash: 5d6962db48941e009166b94e6def7570)
interface __BaseEnv_CloudflareBindings {
	ERASURE_TOMBSTONES: R2Bucket;
	ENVIRONMENT: "local" | "staging";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface LocalEnv {
		ERASURE_TOMBSTONES: R2Bucket;
		ENVIRONMENT: "local";
	}
	interface StagingEnv {
		ERASURE_TOMBSTONES: R2Bucket;
		ENVIRONMENT: "staging";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
