/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings worker-bindings.d.ts` (hash: 8a43f34ce37a718cd6b71fb768a1a047)
interface __BaseEnv_CloudflareBindings {
	ERASURE_TOMBSTONES: R2Bucket;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "local" | "staging";
	PROMOTION_AUTHORITY_FAULTS: DurableObjectNamespace<import("./src/index").PromotionAuthorityFaultDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "PromotionAuthorityFaultDO";
	}
	interface LocalEnv {
		ERASURE_TOMBSTONES: R2Bucket;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "local";
		PROMOTION_AUTHORITY_FAULTS: DurableObjectNamespace<import("./src/index").PromotionAuthorityFaultDO>;
	}
	interface StagingEnv {
		ERASURE_TOMBSTONES: R2Bucket;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "staging";
		PROMOTION_AUTHORITY_FAULTS: DurableObjectNamespace<import("./src/index").PromotionAuthorityFaultDO>;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
