/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings worker-bindings.d.ts` (hash: b94ac7ec3e09e365b5d92b8b708d6524)
interface __BaseEnv_CloudflareBindings {
	ERASURE_TOMBSTONES: R2Bucket;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "local" | "staging";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface LocalEnv {
		ERASURE_TOMBSTONES: R2Bucket;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "local";
	}
	interface StagingEnv {
		ERASURE_TOMBSTONES: R2Bucket;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "staging";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
