/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings worker-bindings.d.ts` (hash: a6fc2f8b7fa54799ce2f2cd6d75d845a)
interface __BaseEnv_CloudflareBindings {
	PUNKS_UI_ORIGIN: "http://localhost:1420";
	API: Fetcher /* punks-api */;
	AUTH: Fetcher /* punks-auth */;
	AUTH_DEV_BOOTSTRAP: Service /* entrypoint LocalDevAuthBootstrapService from punks-auth */;
	API_DEV_BOOTSTRAP: Service /* entrypoint LocalDevApiBootstrapService from punks-api */;
	BOT_WAKE_TRIGGER: Service /* entrypoint BotWakeTriggerService from punks-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUNKS_UI_ORIGIN">> {}
}
