import path from "node:path";
import { defineConfig, loadEnv } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

import { isPunksDistribution } from "./scripts/punks-product-entry.mjs";

const host = process.env.TAURI_DEV_HOST;

export default defineConfig(async ({ mode }) => {
  const loadedEnvironment = loadEnv(mode, process.cwd(), "");
  const punks = isPunksDistribution({
    ...process.env,
    ...loadedEnvironment,
  });

  return {
    root: punks ? path.resolve(__dirname, "punks-product") : undefined,
    plugins: [
      ...(punks
        ? []
        : [
            tanstackRouter({
              target: "react",
              routesDirectory: "./src/app/routes",
              generatedRouteTree: "./src/app/routeTree.gen.ts",
              virtualRouteConfig: "./src/app/routes.ts",
              quoteStyle: "double",
              semicolons: true,
              routeTreeFileHeader: [
                "// biome-ignore-all lint: generated by TanStack Router",
              ],
            }),
          ]),
      react(),
    ],
    publicDir: punks ? false : "public",
    build: punks
      ? {
          emptyOutDir: true,
          outDir: path.resolve(__dirname, "dist"),
        }
      : undefined,
    resolve: {
      alias: {
        "@": path.resolve(__dirname, "src"),
        "@features-manifest": path.resolve(
          __dirname,
          "../preview-features.json",
        ),
        "@model-capabilities-manifest": path.resolve(
          __dirname,
          "../scripts/model-capabilities.json",
        ),
      },
    },

    // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
    //
    // 1. prevent Vite from obscuring rust errors
    clearScreen: false,
    // 2. tauri expects a fixed port, fail if that port is not available
    server: {
      port: parseInt(process.env.VITE_PORT || "1420", 10),
      strictPort: true,
      host: host || false,
      hmr: host
        ? {
            protocol: "ws",
            host,
            port: parseInt(process.env.VITE_HMR_PORT || "1421", 10),
          }
        : undefined,
      watch: {
        // 3. tell Vite to ignore watching `src-tauri`
        ignored: ["**/src-tauri/**"],
      },
    },
  };
});
